### ISSUE TITLE
Add support for threads

### ISSUE THREAD

**Issue by sebz** [AirVantage/hubot-jira-issue-fetcher#2]
CCBot answers in the channel instead of the thread.

**Comment by sebz** [comment]
After investigating it seems that hubot-slack adapter I rely on, does not support it yet...

In fact when someone talks in a thread I receive the message twice, from the channel and the thread.

**Comment by jvermillard** [comment]
https://github.com/slackapi/hubot-slack/issues/393 :wink:

**Comment by jvermillard** [comment]
:tada: :tada: :sparkles: 
happy bastille day :D http://www.bastilledayfestival.ca/
